name: postgres-ai
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: postgres-ai:v1
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./activate-extension.sql:/docker-entrypoint-initdb.d/0-activate_extension.sql

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vectordb
      - OPENAI_API_KEY=sk-asdasd

  vectorizer-worker:
    image: timescale/pgai-vectorizer-worker:latest
    environment:
      PGAI_VECTORIZER_WORKER_DB_URL: postgres://postgres:postgres@postgres:5432/vectordb
      OPENAI_API_KEY: sk-asdasd
    command: [ "--poll-interval", "60s" ]
