# -*- coding: utf-8 -*-
"""Code2_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KhDNKig5XnHy8ciQqXeJKnYRbeaZ2ZNx

# 🐍 Exemplo de bigramas

Exemplo prático do capítulo: 2.5 Exemplo prático (N-Gram)
"""

# @title Importação dos pacote

from collections import defaultdict, Counter
import re

# @title Texto de exemplo

texto = """
O gato dorme no sofá. O cachorro dorme na cama. O gato e o cachorro são amigos.
"""

# @title 1 - Pre-processamento do texto um pequena tokenização

tokens = re.findall(r'\b\w+\b', texto.lower())
tokens

# @title 2 - Contagem do bigramas para verificarmos a frequência

bigramas = [(tokens[i], tokens[i+1]) for i in range(len(tokens)-1)]
bigramas_frequencia = Counter(bigramas)
bigramas_frequencia

# @title 3 - Conatagem das palavras individuais - faremos isso para realizar o cálculo de probabilidade

unigrama_frequencia = Counter(tokens)
unigrama_frequencia

# @title 4 - Probabilidade condicional

probabilidades = defaultdict(dict)
for bigrama, frequencia in bigramas_frequencia.items():
    palavra1, palavra2 = bigrama
    probabilidades[palavra1][palavra2] = frequencia / unigrama_frequencia[palavra1]

# @title 5 - Frequência dos bigramas

for bigrama, freq in bigramas_frequencia.items():
    print(f"{bigrama}: {freq}")

# @title 6 - Probabilidade condicional: P(palavra2 | palavra1)

for palavra1 in probabilidades:
  for palavra2 in probabilidades[palavra1]:
    print(f"P({palavra2} | {palavra1}) = {probabilidades[palavra1][palavra2]}")

# @title 7 - Prever a palavra

def prever_proxima(palavra):
    if palavra in probabilidades:
        seguintes = probabilidades[palavra]
        mais_provavel = max(seguintes, key=seguintes.get)
        return mais_provavel
    else:
        return "desconhecido"

# @title 8 - Resultado

print(prever_proxima("gato"))