[project]
name = "backagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "eventlet>=0.40.0",
    "flask>=3.1.1",
    "flask-cors>=6.0.1",
    "flask-jwt-extended>=4.7.1",
    "flask-socketio>=5.5.1",
    "flask-sqlalchemy>=3.1.1",
    "google-auth>=2.40.3",
    "gunicorn>=23.0.0",
    "langchain>=0.3.26",
    "langchain-ollama>=0.3.3",
    "langchain-openai>=0.3.27",
    "markdown>=3.8.2",
    "ollama>=0.5.1",
    "openai>=1.93.0",
    "psycopg2-binary>=2.9.10",
    "pydantic>=2.11.7",
    "python-dotenv>=1.1.1",
    "stripe>=12.2.0",
]
